dataDir: "/LAB-DATA/GLiCID/projects/CRCI2NA_DATA/ICAGEN/MIDAS/Analyses/RNA-seq/METABOLISM/HUMESS/models/edgeR/MIDAS_exp.cluster/output"
outDir: "/scratch/nautilus/users/sanglier-l@univ-nantes.fr/Midasbolism/pipeline/results"
models:
  - CD1
  - CD2
  - HP1
  - HP2
  - HP3
  - LB
  - MF
  - MN
  - MS
