import os
import pandas as pd

configfile: "../config/config-glicid-scratch.yml"


# Outputs for rule all()
def all_outputs():
    outputs = []

    for model in config["models"]:

        outputs.append(
            f"{config['outDir']}/{model}/pca_fs/{model}_pca.tsv"
        )

        outputs.append(
            f"{config['outDir']}/{model}/pca_fs/{model}_pca.png"
        )

        outputs.append(
            f"{config['outDir']}/{model}/umap_fs/{model}_umap.tsv"
        )

        outputs.append(
            f"{config['outDir']}/{model}/umap_fs/{model}_umap.png"
        )

        outputs.append(
            f"{config['outDir']}/{model}/rcc/{model}_rcc.png"
        )

        outputs.append(
            f"{config['outDir']}/{model}/rcc/{model}_rcc_with_gp.png"
        )

        outputs.append(
            f"{config['outDir']}/{model}/gapfilling/{model}_gapfilled.tsv"
        )

        outputs.append(
            f"{config['outDir']}/{model}/report/{model}.report.html"
        )

        outputs.append(
            f"{config['outDir']}/all/pca_median_fs/median_flux_matrix.tsv"
        )

        outputs.append(
            f"{config['outDir']}/all/pca_median_fs/pca.tsv"
        )
        outputs.append(
            f"{config['outDir']}/all/pca_median_fs/pca.png"
        )
        outputs.append(
            f"{config['outDir']}/all/pca_all_fs/pca_all_fs.png"
        )
    return outputs


# RULE ALL
rule all:
    input:
        all_outputs()



# PCA
rule pc_fs:
    input:
        fs=f"{config['dataDir']}/models/{{models}}/fs/fs_{{models}}.tsv"
    output:
        pca=f"{config['outDir']}/{{models}}/pca_fs/{{models}}_pca.tsv",
        var = f"{config['outDir']}/{{models}}/pca_fs/{{models}}_pca_var.tsv",
    log:
        f"{config['outDir']}/log/pca_fs/{{models}}_pca.log"
    params:
        n=20000,
        seed=42,
        sampling=False  
    conda:
        "envs/env.yml"
    threads: 3
    script:
        "scripts/pca_fs.R"


rule plot_pca:
    input:
        pca=f"{config['outDir']}/{{models}}/pca_fs/{{models}}_pca.tsv",
        var=f"{config['outDir']}/{{models}}/pca_fs/{{models}}_pca_var.tsv"
    output:
        png=f"{config['outDir']}/{{models}}/pca_fs/{{models}}_pca.png"
    conda:
        "envs/env.yml"
    threads: 1
    script:
        "scripts/plot_pca.R"


#UMAP (on PCs)
rule umap_fs:
    input:
        pca=f"{config['outDir']}/{{models}}/pca_fs/{{models}}_pca.tsv"
    output:
        umap=f"{config['outDir']}/{{models}}/umap_fs/{{models}}_umap.tsv"
    conda:
        "envs/env.yml"
    threads: 1
    script:
        "scripts/umap_fs.R"


rule plot_umap:
    input:
        umap=f"{config['outDir']}/{{models}}/umap_fs/{{models}}_umap.tsv"
    output:
        png=f"{config['outDir']}/{{models}}/umap_fs/{{models}}_umap.png"
    conda:
        "envs/env.yml"
    threads: 1
    script:
        "scripts/plot_umap.R"


#RCC script Louis Paré
rule plot_rcc:
    input:
        fs=f"{config['dataDir']}/models/{{models}}/fs/fs_{{models}}.tsv"
    output:
        png=f"{config['outDir']}/{{models}}/rcc/{{models}}_rcc.png"
    conda:
        "envs/env.yml"
    threads: 1
    script:
        "scripts/plot_rcc.R"

# script adapted to Louis Paré
rule plot_rcc_gp:
    input:
        fs=f"{config['dataDir']}/models/{{models}}/fs/fs_{{models}}.tsv",
        gp_status=f"{config['outDir']}/{{models}}/gapfilling/{{models}}_gapfilled.tsv"
    output:
        png=f"{config['outDir']}/{{models}}/rcc/{{models}}_rcc_with_gp.png"
    conda:
        "envs/env.yml"
    threads: 1
    script:
        "scripts/plot_rcc_gp.R"



rule flag_gapfilled:
    input:
        carveme=f"{config['dataDir']}/models/{{models}}/stats/carveme.reactions.list",
        srp=f"{config['dataDir']}/models/{{models}}/stats/srp.reactions.list"
    output:
        tsv=f"{config['outDir']}/{{models}}/gapfilling/{{models}}_gapfilled.tsv"
    conda:
        "envs/env.yml"
    threads: 1
    script:
        "scripts/flag_gapfilled.R"


rule median_flux_matrix:
    input:
        expand(
            f"{config['dataDir']}/models/{{model}}/fs/fs_{{model}}.tsv",
            model=config["models"]
        )
    output:
        tsv=f"{config['outDir']}/all/pca_median_fs/median_flux_matrix.tsv"
    log:
        f"{config['outDir']}/log/median_fs/median_flux_matrix.log"
    conda:
        "envs/env.yml"
    script:
        "scripts/median_flux_matrix.R"


# PCA on median_fs
rule pc_median_fs:
    input:
        fs=f"{config['outDir']}/all/pca_median_fs/median_flux_matrix.tsv"
    output:
        pca=f"{config['outDir']}/all/pca_median_fs/pca.tsv",
        var=f"{config['outDir']}/all/pca_median_fs/pca_var.tsv"
    log:
        f"{config['outDir']}/log/pca_median_fs/pca.log"
    conda:
        "envs/env.yml"
    threads: 3
    script:
        "scripts/pca_median_fs.R"

rule plot_pca_median_fs:
    input:
        pca=f"{config['outDir']}/all/pca_median_fs/pca.tsv",
        var=f"{config['outDir']}/all/pca_median_fs/pca_var.tsv"
    output:
        png=f"{config['outDir']}/all/pca_median_fs/pca.png"
    conda:
        "envs/env.yml"
    threads: 1
    script:
        "scripts/plot_pca_median_fs.R"

rule all_flux_matrix:
    input:
        expand(
            f"{config['dataDir']}/models/{{model}}/fs/fs_{{model}}.tsv",
            model=config["models"]
        )
    output:
        png=f"{config['outDir']}/all/pca_all_fs/pca_all_fs.png"
    log:
        f"{config['outDir']}/log/pca_all_fs/pca_sampling.log"
    conda:
        "envs/env.yml"
    threads: 4
    script:
        "scripts/all_flux_matrix.R"

#HTML reports for each models
rule render_report:
    input:
        qmd="scripts/report_humess.qmd",
        fs=f"{config['dataDir']}/models/{{models}}/fs/fs_{{models}}.tsv",
        pca=f"{config['outDir']}/{{models}}/pca_fs/{{models}}_pca.tsv",
        umap=f"{config['outDir']}/{{models}}/umap_fs/{{models}}_umap.tsv",
        png_pca=f"{config['outDir']}/{{models}}/pca_fs/{{models}}_pca.png",
        png_umap=f"{config['outDir']}/{{models}}/umap_fs/{{models}}_umap.png",
        png_rcc_gp=f"{config['outDir']}/{{models}}/rcc/{{models}}_rcc_with_gp.png"

    output:
        html=report(
            f"{config['outDir']}/{{models}}/report/{{models}}.report.html",
            category="{models}",
            labels={"model": "{models}"}
        )

    params:
        outdir=f"{config['outDir']}/{{models}}/report",
        models="{models}"

    conda:
        "envs/quarto.yml"

    threads: 1

    log:
        f"{config['outDir']}/{{models}}/report/render_report.log"

    shell:
        r"""
        mkdir -p "{params.outdir}"

        export TMPDIR="${{TMPDIR:-/tmp}}"
        export DENO_DIR="$TMPDIR/quarto-deno-cache-{wildcards.models}"
        export XDG_CACHE_HOME="$TMPDIR/quarto-xdg-cache-{wildcards.models}"

        cp "{input.qmd}" "{params.outdir}/report_humess.qmd"

        cd "{params.outdir}"

        quarto render report_humess.qmd \
            --output "{wildcards.models}.report.html" \
            -P models:"{params.models}" \
            -P outdir:"{params.outdir}" \
            -P fs_file:"{input.fs}" \
            -P png_pca:"{input.png_pca}" \
            -P png_umap:"{input.png_umap}" \
            -P png_rcc_gp:"{input.png_rcc_gp}" \
            > "{log}" 2>&1

        rm -f report_humess.qmd
        """